name: instagram_clone
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0
  flutter_feather_icons: ^2.0.0+1

  #state management
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  

  #Firebase
  cloud_firestore: ^4.9.3
  firebase_storage: ^11.2.8
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_core_platform_interface: 4.8.0


  #Service Locator
  get_it: ^7.2.0


  flutter_svg: ^1.0.3
  image_picker: ^0.8.4+11
  intl: ^0.18.1
  uuid: ^3.0.7
  cached_network_image: ^3.2.0

  #show toast
  fluttertoast: ^8.0.9
  modal_bottom_sheet: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: PlayFair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
        - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
          style: italic
